test_task = [{'area': '2nN2ynMGK84cyws9AZKLo6',
                'area_title': 'Home',
                'created': '2025-06-08 00:00:00',
                'deadline': None,
                'index': -2060,
                'modified': '2025-06-08 16:29:59',
                'notes': '',
                'reminder_time': '15:00',
                'start': 'Anytime',
                'start_date': '2025-06-16',
                'status': 'incomplete',
                'stop_date': None,
                'tags': ['30m'],
                'title': 'Test Item Updated',
                'today_index': 4920975,
                'type': 'to-do',
                'uuid': '12345',
                # 'change_type': 'new',
                # 'calendar_event_id': '2ptun9uehush7mojd94n9rbs3o'
                }]

updated_task = [{'area': '2nN2ynMGK84cyws9AZKLo6',
                'area_title': 'Home',
                'created': '2025-06-08 00:00:00',
                'deadline': None,
                'index': -2060,
                'modified': '2025-06-08 16:29:59',
                'notes': '',
                'reminder_time': '15:00',
                'start': 'Anytime',
                'start_date': '2025-06-17',
                'status': 'incomplete',
                'stop_date': None,
                'tags': ['30m'],
                'title': 'Test Item Updated',
                'today_index': 4920975,
                'type': 'to-do',
                'uuid': '12345',
                # 'change_type': 'new',
                # 'calendar_event_id': '2ptun9uehush7mojd94n9rbs3o'
                }]


current_deadlines = [{'checklist': True,
                        'created': '2025-07-06 22:35:16',
                        'deadline': '2025-07-11',
                        'index': -771,
                        'modified': '2025-07-10 18:23:29',
                        'notes': '',
                        'project': 'XcoBPpSUnKLtA5Sdymrjfy',
                        'project_title': 'PowerThings',
                        'reminder_time': '14:00',
                        'start': 'Anytime',
                        'start_date': '2025-07-11',
                        'status': 'incomplete',
                        'stop_date': None,
                        'title': 'Add Deadline calendar to PowerThings',
                        'today_index': -2698,
                        'type': 'to-do',
                        'uuid': 'Tfv65SLV4z1M19LJQbjc7L'},
                        {'area': 'UqVxNSRc4kXSFB9w9CSuwo',
                        'area_title': 'CourseStorm',
                        'created': '2025-07-08 17:45:35',
                        'deadline': '2025-07-11',
                        'index': -602,
                        'modified': '2025-07-11 13:02:23',
                        'notes': '',
                        'reminder_time': '10:00',
                        'start': 'Anytime',
                        'start_date': '2025-07-11',
                        'status': 'incomplete',
                        'stop_date': None,
                        'tags': ['90m', 'Becky'],
                        'title': 'Work on updating V2 of Churn Query for Becky ',
                        'today_index': -2177,
                        'type': 'to-do',
                        'uuid': 'ST6mBURRX1nbLkd56FLn3'
                        }]

updated_deadlines = [{'checklist': True,
                    'created': '2025-07-06 22:35:16',
                    'deadline': '2025-07-11',
                    'index': -771,
                    'modified': '2025-07-10 18:23:29',
                    'notes': '',
                    'project': 'XcoBPpSUnKLtA5Sdymrjfy',
                    'project_title': 'PowerThings',
                    'reminder_time': '14:00',
                    'start': 'Anytime',
                    'start_date': '2025-07-11',
                    'status': 'incomplete',
                    'stop_date': None,
                    'title': 'Add Deadline calendar to PowerThings',
                    'today_index': -2698,
                    'type': 'to-do',
                    'uuid': 'Tfv65SLV4z1M19LJQbjc7L'}]

deadline_calendar_events = [{'created': '2025-07-17T20:41:48.000Z',
        'creator': {'email': 'heyjohnelliott@gmail.com'},
        'description': 'Qc5SacSpUzHd3benWSGTc9',
        'end': {'date': '2025-07-18'},
        'etag': '"3505569818483742"',
        'eventType': 'default',
        'htmlLink': 'https://www.google.com/calendar/event?eid=cm4zNWY1N3FkaTdqMG5uM3Q5ZmZxcWM2ZW8gOGE3ZjYyYzVkNDQ1MDYzZmMyOWIwNDQxYzNjM2MzOWIwMzNjNzkyZDE5NTQ0NGFkNWNlMTBjNGVhNjhkOTQ3MkBn',
        'iCalUID': 'rn35f57qdi7j0nn3t9ffqqc6eo@google.com',
        'id': 'rn35f57qdi7j0nn3t9ffqqc6eo',
        'kind': 'calendar#event',
        'location': 'things:///show?id=Qc5SacSpUzHd3benWSGTc9',
        'organizer': {'displayName': 'Deadlines',
                        'email': '8a7f62c5d445063fc29b0441c3c3c39b033c792d195444ad5ce10c4ea68d9472@group.calendar.google.com',
                        'self': True},
        'reminders': {'useDefault': False},
        'sequence': 0,
        'start': {'date': '2025-07-18'},
        'status': 'confirmed',
        'summary': 'Look in to bug where adding a new deadline seems to '
                    'delete another ',
        'updated': '2025-07-17T20:41:49.241Z'}]


